Added creation of fragment shader and shader program linking within header file. glGetProgramInfoLog tells me "0(6) : error C1013: function "main" is already defined at 0(7)" which may be due to the separate shader source codes.